id: 34cccff7e5c94adeaf9999cb31f4210f
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_70-The_Sutra_of_the_Question_of_Subahu-v1
  language: en
  author: ''
  volume: {}
